defaults: &defaults
  working_directory: ~/repo
  environment:
    MAVEN_OPTS: -server -showversion -XX:+PrintCommandLineFlags -XX:+UseCodeCacheFlushing -Xms1024M -Xmx2048M -XX:+CMSClassUnloadingEnabled -XX:-OmitStackTraceInFastThrow -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -XX:NewSize=600m -XX:MaxNewSize=900m -XX:SurvivorRatio=10 -XX:+DisableExplicitGC -Djava.security.egd=file:/dev/./urandom

version: 2
jobs:
  build-ruby-2.4.2:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.7.0
    steps:
      - checkout
      - run:
          name: Install gem dependencies
          command: |
            source /usr/share/rvm/scripts/rvm
            rvm use ruby-2.4.2
            bundle install --jobs=4 --retry=3 --path=vendor/bundle
      - save_cache:
          paths:
            - Gemfile.lock
            - .bundle
            - vendor/bundle
          key: v1-dependencies-{{ .Revision }}

  test-mysql-ruby-2.4.2:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.7.0
      - image: killbill/killbill:0.22.11
        environment:
        - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
        - KILLBILL_PAYMENT_PLUGIN_TIMEOUT=5s
        - KILLBILL_DAO_URL=jdbc:mysql://127.0.0.1:3306/killbill
        - KILLBILL_DAO_USER=root
        - KILLBILL_DAO_PASSWORD=root
        - KILLBILL_SERVER_TEST_MODE=true
        - KILLBILL_INVOICE_SANITY_SAFETY_BOUND_ENABLED=false
        - KILLBILL_INVOICE_MAX_DAILY_NUMBER_OF_ITEMS_SAFETY_BOUND=-1
        - KILLBILL_MAIN_QUEUE_MODE=POLLING
        - KILLBILL_NOTIFICATIONQ_MAIN_SLEEP=500
        - KILLBILL_BUS_MAIN_SLEEP=500
        - KILLBILL_BUS_EXTERNAL_SLEEP=500
        - KILLBILL_SECURITY_SHIRO_NB_HASH_ITERATIONS=1
      - image: killbill/mariadb:0.22
        environment:
        - MYSQL_ROOT_PASSWORD=root
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ .Revision }}
      - run:
          name: Setup DDL
          command: |
            set +e
            count=0
            until mysqladmin ping -h 127.0.0.1 -u root --password=root --silent; do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))
              printf '.'
              sleep 5
            done
            set -e
            curl -s https://raw.githubusercontent.com/killbill/killbill-avatax-plugin/master/src/main/resources/ddl.sql > /var/tmp/avatax.ddl
            mysql -uroot -proot -h 127.0.0.1 -D killbill < /var/tmp/avatax.ddl
      - run:
          name: Setup Kill Bill
          command: |
            set +e
            count=0
            until $(curl --output /dev/null --silent --fail http://127.0.0.1:8080/1.0/healthcheck); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))

              printf '.'
              sleep 5
            done
            set -e
            curl -v \
                 -X POST \
                 -u admin:password \
                 -H 'Content-Type: application/json' \
                 -H 'X-Killbill-CreatedBy: CircleCI' \
                 -d '{"apiKey": "bob", "apiSecret": "lazar"}' \
                 "http://127.0.0.1:8080/1.0/kb/tenants?useGlobalDefault=true"
      - run:
          name: Run tests
          command: |
            source /usr/share/rvm/scripts/rvm
            rvm use ruby-2.4.2
            # Until plugins are released
            #bundle exec rake ci:all TESTOPTS="--stop-on-failure"
            bundle exec rake ci:core TESTOPTS="--stop-on-failure"
      - store_test_results:
          path: test/reports/
      - store_artifacts:
          path: test/reports/

  test-postgresql-ruby-2.4.2:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.7.0
      - image: killbill/killbill:0.22.11
        environment:
        - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
        - KILLBILL_PAYMENT_PLUGIN_TIMEOUT=5s
        - KILLBILL_DAO_URL=jdbc:postgresql://127.0.0.1:5432/killbill
        - KILLBILL_DAO_USER=postgres
        - KILLBILL_DAO_PASSWORD=postgres
        - KILLBILL_SERVER_TEST_MODE=true
        - KILLBILL_INVOICE_SANITY_SAFETY_BOUND_ENABLED=false
        - KILLBILL_INVOICE_MAX_DAILY_NUMBER_OF_ITEMS_SAFETY_BOUND=-1
        - KILLBILL_MAIN_QUEUE_MODE=POLLING
        - KILLBILL_NOTIFICATIONQ_MAIN_SLEEP=500
        - KILLBILL_BUS_MAIN_SLEEP=500
        - KILLBILL_BUS_EXTERNAL_SLEEP=500
        - KILLBILL_SECURITY_SHIRO_NB_HASH_ITERATIONS=1
      - image: killbill/postgresql:0.22
        environment:
        - POSTGRES_PASSWORD=postgres
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ .Revision }}
      - run:
          name: Setup DDL
          command: |
            set +e
            count=0
            until $(psql -h 127.0.0.1 -U postgres -p 5432 killbill -c 'select 1' > /dev/null); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))
              printf '.'
              sleep 5
            done
            set -e
            curl -s https://raw.githubusercontent.com/killbill/killbill-avatax-plugin/master/src/main/resources/ddl-postgresql.sql > /var/tmp/avatax.ddl
            curl -s https://raw.githubusercontent.com/killbill/killbill-avatax-plugin/master/src/main/resources/ddl.sql >> /var/tmp/avatax.ddl
            psql -h 127.0.0.1 -U postgres -p 5432 killbill < /var/tmp/avatax.ddl
      - run:
          name: Setup Kill Bill
          command: |
            set +e
            count=0
            until $(curl --output /dev/null --silent --fail http://127.0.0.1:8080/1.0/healthcheck); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))

              printf '.'
              sleep 5
            done
            set -e
            curl -v \
                 -X POST \
                 -u admin:password \
                 -H 'Content-Type: application/json' \
                 -H 'X-Killbill-CreatedBy: CircleCI' \
                 -d '{"apiKey": "bob", "apiSecret": "lazar"}' \
                 "http://127.0.0.1:8080/1.0/kb/tenants?useGlobalDefault=true"
      - run:
          name: Run tests
          command: |
            source /usr/share/rvm/scripts/rvm
            rvm use ruby-2.4.2
            # Until plugins are released
            #bundle exec rake ci:all TESTOPTS="--stop-on-failure"
            bundle exec rake ci:core TESTOPTS="--stop-on-failure"
      - store_test_results:
          path: test/reports/
      - store_artifacts:
          path: test/reports/

  test-rubocop:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.7.0
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ .Revision }}
      - run:
          name: Run RuboCop
          command: |
            mkdir /tmp/test-results
            source /usr/share/rvm/scripts/rvm
            rvm use ruby-2.4.2
            bundle exec rubocop --format tap | tee /tmp/test-results/rubocop.txt 2>&1
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-ruby-2.4.2
      - test-rubocop:
          requires:
            - build-ruby-2.4.2
      - test-mysql-ruby-2.4.2:
          requires:
            - build-ruby-2.4.2
      - test-postgresql-ruby-2.4.2:
          requires:
            - build-ruby-2.4.2